name: Lint and Typing
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - run: pip install .[lint]
  linter:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - run: ruff check src
    - run: ruff format --check src
  typechecker:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - run: mypy --strict src
